# Config used for local development.
# All dependent services (NSQ, Couchbase, ..) are assumed running in the
# same context.

# General app config.
address = ":8080" # The IP:Port. Defaults to 8080.
log_level = "debug" # Log level. Defaults to info.
disable_cors = true # Disable CORS policy.
jwt_signkey = "secret" # JWT sign key secret.
jwt_expiration = 72 # JWT expiration in hours. Defaults to 72 hours (3 days).
reset_pwd_token_expiration = 10 # represents the token expiration for reset password and email confirmation requests in minutes.
max_file_size = 64 # Maximum file size to allow for samples in MB.
max_avatar_file_size = 1 # Maximum avatar size to allow for user profile picture in KB.

[ui]
address = "http://localhost:8000" # DSN for the frontend.

[db]
server = "couchbase://localhost" # DSN for connecting to the database
username = "Administrator" # Username used to access the db.
password = "password" # Password used to access the db.
bucket_name = "sfw" # Name of the couchbase bucket.

[nsq]
address = "localhost:4150" # The data source name (DSN) for connecting to the broker server (NSQD).
topic = "topic-filescan" # Topic name to produce to.

[storage]
deployment_kind = "local" # Deployement kind, possible values: aws, minio, local.
files_container_name = "saferwall-samples" # Container name for samples.
avatars_container_name = "saferwall-images" # Container name for avatars.
    # Only one storage type has to be provided. `deployment_kind` controls
    # at runtime which one to use.
    [storage.s3]
    region = "us-east-1" # AWS region.
    access_key = "AwsAccessKey" # AWS Secret Access Key.
    secret_key = "AwsSecretKey" # AWS Access key ID.
    [storage.minio]
    endpoint = "localhost:9000" # MinIO endpoint.
    region = "us-east-1" # Region.
    access_key = "minio" # Access key ID.
    secret_key = "minio123" # Secret Access Key.
    [storage.local]
    root_dir = "/saferwall" # Full path to the directory where to store the files.

[smtp]
server = "" # for example: smtp.example.com
port = 587
user = "user@example.com"
password = "password"
identity = "identity"
sender = "sender@example.com"
